# Generated by Django 5.2.7 on 2025-10-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shkarik', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.AddField(
            model_name='order',
            name='public_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='secret_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
