# Generated by Django 5.2.7 on 2025-10-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shkarik', '0003_remove_order_order_number_order_public_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='public_code',
            field=models.CharField(default='DEFOLT', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='secret_code',
            field=models.CharField(default='DEFOLTT', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
