# Generated by Django 5.2.7 on 2025-10-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shkarik', '0004_alter_order_public_code_alter_order_secret_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'В очереди'), ('cooking', 'Готовится'), ('ready', 'Готов'), ('delivering', 'Доставляется'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='new', max_length=20),
        ),
    ]
