# Generated by Django 5.2.7 on 2025-10-31 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shkarik', '0006_courier_order_courier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier',
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
    ]
