# Generated by Django 5.2.7 on 2025-11-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shkarik', '0007_remove_order_courier_delete_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
