# Generated by Django 5.2.7 on 2025-11-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shkarik', '0008_order_accepted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя курьера')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код доступа')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
            },
        ),
    ]
