# Generated by Django 5.2.7 on 2025-11-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shkarik', '0010_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершение доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало доставки'),
        ),
    ]
