# Generated by Django 5.2.7 on 2025-11-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shkarik', '0011_order_delivery_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_completed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_started_at',
        ),
    ]
